pipeline:
  identifier: Build_phonomenal_wordsmith_demo_1707322762939
  name: Build wordsmith-demo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1707322479937
        repoName: phonomenal/wordsmith-demo
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: jameslehadockerregistry
                    image: maven
                    shell: Sh
                    command: |
                      mvn -version
                      mvn clean package dependency:copy-dependencies -f api/pom.xml 
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    connectorRef: jameslehadockerregistry
                    image: maven
                    language: Java
                    buildTool: Maven
                    args: test -f api
                    packages: io.harness
                    runOnlySelectedTests: true
                    postCommand: mvn package -DskipTests
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
                    enableTestSplitting: false
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: jameslehadockerregistry
                    repo: jamesleha/wordsmith-app
                    tags:
                      - <+pipeline.sequenceId>
