pipeline:
  identifier: Build_phonomenal_wordsmith_demo_1707322762939
  name: Build wordsmith-demo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1707322479937
        repoName: phonomenal/wordsmith-demo
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build-and-test
                  identifier: build
                  spec:
                    connectorRef: jameslehadockerregistry
                    image: maven
                    shell: Sh
                    command: |-
                      mvn -version
                      mvn clean package dependency:copy-dependencies -f api/pom.xml 
                      mvn test -Dtest=JUnit5TestCases -f api/pom.xml    
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push to Docker
                  identifier: Build_and_push_to_Docker
                  spec:
                    connectorRef: githubcontainerregistry
                    repo: ghcr.io/phonomenal/wordsmith-demo
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: api/Dockerfile
                    context: api/
