pipeline:
  identifier: Build_phonomenal_wordsmith_demo_1707322762939
  name: Build wordsmith-demo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1707322479937
        repoName: phonomenal/wordsmith-demo
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: build-and-test
                  identifier: build
                  template:
                    templateRef: Maven_Build_and_Test
                    versionLabel: v1
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push to GHCR
                  identifier: Build_and_push_to_ghcr
                  spec:
                    connectorRef: githubcontainerregistry
                    repo: ghcr.io/phonomenal/wordsmith-demo
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: api/Dockerfile
                    context: api/
    - stage:
        name: K8s Deploy
        identifier: K8s_Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: harnessguestbook
          environment:
            environmentRef: harnessdevenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
